## Aproveitamento do Manchester United com Bruno Fernandes em campo:

In [40]:
import pandas as pd

In [41]:
dados = {
    'jogo_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'data': ['2024-08-01', '2024-08-05', '2024-08-12', '2024-08-20', '2024-08-27', '2024-09-02', '2024-09-09', '2024-09-15'],
    'bruno_fernandes_em_campo': [True, False, True, True, False, True, False, True],
    'vitoria': [True, False, True, False, False, True, True, True],
    'empate': [False, True, False, False, True, False, False, False]
}

In [42]:
aproveitamento_bf = pd.DataFrame(dados)

In [43]:
aproveitamento_bf

   jogo_id        data  bruno_fernandes_em_campo  vitoria  empate
0        1  2024-08-01                      True     True   False
1        2  2024-08-05                     False    False    True
2        3  2024-08-12                      True     True   False
3        4  2024-08-20                      True    False   False
4        5  2024-08-27                     False    False    True
5        6  2024-09-02                      True     True   False
6        7  2024-09-09                     False     True   False
7        8  2024-09-15                      True     True   False

In [44]:
aproveitamento_bf.info() #Conclui-se que data não está no formato correto

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   jogo_id                   8 non-null      int64
 1   data                      8 non-null      object
 2   bruno_fernandes_em_campo  8 non-null      bool
 3   vitoria                   8 non-null      bool
 4   empate                    8 non-null      bool
dtypes: bool(3), int64(1), object(1)
memory usage: 284.0+ bytes

In [45]:
from datetime import datetime

In [50]:
#Necessária a conversão do tipo string para datetime na coluna 'data'
aproveitamento_bf['data'] = pd.to_datetime(aproveitamento_bf['data'])

In [51]:
aproveitamento_bf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   jogo_id                   8 non-null      int64
 1   data                      8 non-null      datetime64[ns]
 2   bruno_fernandes_em_campo  8 non-null      bool
 3   vitoria                   8 non-null      bool
 4   empate                    8 non-null      bool
dtypes: bool(3), datetime64[ns](1), int64(1)
memory usage: 284.0 bytes

In [52]:
#Determine o aproveitamento de pontos do Manchester United em partidas onde Bruno Fernandes está em campo:
aproveitamento_bf

   jogo_id       data  bruno_fernandes_em_campo  vitoria  empate
0        1 2024-08-01                      True     True   False
1        2 2024-08-05                     False    False    True
2        3 2024-08-12                      True     True   False
3        4 2024-08-20                      True    False   False
4        5 2024-08-27                     False    False    True
5        6 2024-09-02                      True     True   False
6        7 2024-09-09                     False     True   False
7        8 2024-09-15                      True     True   False

In [55]:
quantidade_jogos = len(aproveitamento_bf['jogo_id'])
quantidade_jogos #Número de partidas

8

In [60]:
partidas_bf = 0
soma_pontos = 0
for i in range(len(aproveitamento_bf['bruno_fernandes_em_campo'])):
    if aproveitamento_bf['bruno_fernandes_em_campo'][i] == True:
        partidas_bf = partidas_bf + 1
        if ((aproveitamento_bf['vitoria'][i] == True) & (aproveitamento_bf['empate'][i] == False)): #Vitória
            soma_pontos = soma_pontos + 3
        elif ((aproveitamento_bf['vitoria'][i] == False) & (aproveitamento_bf['empate'][i] == True)): #Empate
             soma_pontos = soma_pontos + 1
        elif ((aproveitamento_bf['vitoria'][i] == False) & (aproveitamento_bf['empate'][i] == False)): #Derrota
            soma_pontos = soma_pontos + 0
        else: #Qualquer outro caso (inexistente)
            print('Erro no Conjunto de Dados') 
            break
    else:
        partidas_bf = partidas_bf + 0

In [61]:
partidas_bf

5

In [62]:
soma_pontos

12

In [65]:
#Sabendo-se quem cada partida, o máximo de pontos possível é 3:
total_pontos = partidas_bf * 3

#Dessa forma, checa-se o aproveitamento do clube enquanto Bruno Fernando esteve em campo:
print(f'O aproveitamento de pontos com Bruno Fernandes em campo é de {round((soma_pontos / total_pontos) * 100, 2)}%')

O aproveitamento de pontos com Bruno Fernandes em campo é de 80.0%

## Média de gols tomados por partida quando o defensor Raphael Varane não joga:

In [67]:
dados = {
    'jogo_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'data': ['2024-08-01', '2024-08-05', '2024-08-12', '2024-08-20', '2024-08-27', '2024-09-02', '2024-09-09', '2024-09-15'],
    'raphael_varane_em_campo': [True, False, True, False, True, False, True, False],
    'gols_sofridos': [1, 3, 0, 2, 1, 4, 1, 3]
}

In [69]:
dados_varane = pd.DataFrame(dados)

In [70]:
dados_varane

   jogo_id        data  raphael_varane_em_campo  gols_sofridos
0        1  2024-08-01                     True              1
1        2  2024-08-05                    False              3
2        3  2024-08-12                     True              0
3        4  2024-08-20                    False              2
4        5  2024-08-27                     True              1
5        6  2024-09-02                    False              4
6        7  2024-09-09                     True              1
7        8  2024-09-15                    False              3

In [72]:
dados_varane.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   jogo_id                  8 non-null      int64
 1   data                     8 non-null      object
 2   raphael_varane_em_campo  8 non-null      bool
 3   gols_sofridos            8 non-null      int64
dtypes: bool(1), int64(2), object(1)
memory usage: 332.0+ bytes

In [73]:
#Convertendo data para datetime:
dados_varane['data'] = pd.to_datetime(dados_varane['data'])

In [74]:
dados_varane.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   jogo_id                  8 non-null      int64
 1   data                     8 non-null      datetime64[ns]
 2   raphael_varane_em_campo  8 non-null      bool
 3   gols_sofridos            8 non-null      int64
dtypes: bool(1), datetime64[ns](1), int64(2)
memory usage: 332.0 bytes

In [75]:
#Calcule a média de gols sofridos por partida quando Raphael Varane não está em campo:
dados_varane

   jogo_id       data  raphael_varane_em_campo  gols_sofridos
0        1 2024-08-01                     True              1
1        2 2024-08-05                    False              3
2        3 2024-08-12                     True              0
3        4 2024-08-20                    False              2
4        5 2024-08-27                     True              1
5        6 2024-09-02                    False              4
6        7 2024-09-09                     True              1
7        8 2024-09-15                    False              3

In [87]:
jogos_sem_varane = 0
gols_tomados = 0

for i in range(len(dados_varane['raphael_varane_em_campo'])):
    if dados_varane['raphael_varane_em_campo'][i] == False:
        jogos_sem_varane = jogos_sem_varane + 1
        gols_tomados = gols_tomados + dados_varane['gols_sofridos'][i]

print(f'Varane não jogou {jogos_sem_varane} partidas. Em suas ausências, a equipe levou {gols_tomados} gols. ')
print(f'Com isso, a média de gols tomados sem o francês em campo foi de {round((gols_tomados / jogos_sem_varane), 2)} por partida.')

Varane não jogou 4 partidas. Em suas ausências, a equipe levou 12 gols.
Com isso, a média de gols tomados sem o francês em campo foi de 3.0 por partida.

## Proporção de vitórias fora de casa sem a presença de Casemiro em campo:

In [88]:
dados = {
    'jogo_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'data': ['2024-08-01', '2024-08-05', '2024-08-12', '2024-08-20', '2024-08-27', '2024-09-02', '2024-09-09', '2024-09-15'],
    'casemiro_em_campo': [True, False, True, False, True, False, True, False],
    'local': ['casa', 'fora', 'casa', 'fora', 'casa', 'fora', 'casa', 'fora'],
    'vitoria': [True, False, True, True, False, True, True, False]
}

In [89]:
dados_casemiro = pd.DataFrame(dados)

In [90]:
dados_casemiro

   jogo_id        data  casemiro_em_campo local  vitoria
0        1  2024-08-01               True  casa     True
1        2  2024-08-05              False  fora    False
2        3  2024-08-12               True  casa     True
3        4  2024-08-20              False  fora     True
4        5  2024-08-27               True  casa    False
5        6  2024-09-02              False  fora     True
6        7  2024-09-09               True  casa     True
7        8  2024-09-15              False  fora    False

In [92]:
dados_casemiro.info() #Novamente a coluna data não esta em formato correto

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   jogo_id            8 non-null      int64
 1   data               8 non-null      object
 2   casemiro_em_campo  8 non-null      bool
 3   local              8 non-null      object
 4   vitoria            8 non-null      bool
dtypes: bool(2), int64(1), object(2)
memory usage: 340.0+ bytes

In [93]:
dados_casemiro['data'] = pd.to_datetime(dados_casemiro['data'])

In [94]:
dados_casemiro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   jogo_id            8 non-null      int64
 1   data               8 non-null      datetime64[ns]
 2   casemiro_em_campo  8 non-null      bool
 3   local              8 non-null      object
 4   vitoria            8 non-null      bool
dtypes: bool(2), datetime64[ns](1), int64(1), object(1)
memory usage: 340.0+ bytes

In [95]:
##Calcule a proporção de vitórias fora de casa em partidas onde Casemiro não jogou:
dados_casemiro

   jogo_id       data  casemiro_em_campo local  vitoria
0        1 2024-08-01               True  casa     True
1        2 2024-08-05              False  fora    False
2        3 2024-08-12               True  casa     True
3        4 2024-08-20              False  fora     True
4        5 2024-08-27               True  casa    False
5        6 2024-09-02              False  fora     True
6        7 2024-09-09               True  casa     True
7        8 2024-09-15              False  fora    False

In [97]:
jogos_sem_casemiro_fora = 0
vitorias_fora_sem_casemiro = 0

for i in range(len(dados_casemiro['casemiro_em_campo'])):
    if ((dados_casemiro['casemiro_em_campo'][i] == False) & (dados_casemiro['local'][i] == 'fora')):
        jogos_sem_casemiro_fora = jogos_sem_casemiro_fora + 1
        if dados_casemiro['vitoria'][i] == True:
            vitorias_fora_sem_casemiro = vitorias_fora_sem_casemiro + 1

In [98]:
jogos_sem_casemiro_fora

4

In [99]:
vitorias_fora_sem_casemiro

2

In [101]:
print(f'O M. United tem uma proporção de {vitorias_fora_sem_casemiro / jogos_sem_casemiro_fora} vitórias quando Casemiro não atua fora de casa.')

O M. United tem uma proporção de 0.5 vitórias quando Casemiro não atua fora de casa.

## Relação entre posse de bola e vitórias com Marcus Rashford no time:

In [102]:
dados = {
    'jogo_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'data': ['2024-08-01', '2024-08-05', '2024-08-12', '2024-08-20', '2024-08-27', '2024-09-02', '2024-09-09', '2024-09-15'],
    'marcus_rashford_em_campo': [True, True, False, True, False, True, True, False],
    'posse_de_bola': [55, 48, 52, 63, 45, 57, 60, 49],
    'vitoria': [True, False, False, True, False, True, True, False]
}

In [103]:
dados_rashford = pd.DataFrame(dados)

In [104]:
dados_rashford

   jogo_id        data  marcus_rashford_em_campo  posse_de_bola  vitoria
0        1  2024-08-01                      True             55     True
1        2  2024-08-05                      True             48    False
2        3  2024-08-12                     False             52    False
3        4  2024-08-20                      True             63     True
4        5  2024-08-27                     False             45    False
5        6  2024-09-02                      True             57     True
6        7  2024-09-09                      True             60     True
7        8  2024-09-15                     False             49    False

In [105]:
dados_rashford.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   jogo_id                   8 non-null      int64
 1   data                      8 non-null      object
 2   marcus_rashford_em_campo  8 non-null      bool
 3   posse_de_bola             8 non-null      int64
 4   vitoria                   8 non-null      bool
dtypes: bool(2), int64(2), object(1)
memory usage: 340.0+ bytes

In [108]:
dados_rashford['data'] = pd.to_datetime(dados_rashford['data'])

In [110]:
dados_rashford.info() #Dqdos convertidos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   jogo_id                   8 non-null      int64
 1   data                      8 non-null      datetime64[ns]
 2   marcus_rashford_em_campo  8 non-null      bool
 3   posse_de_bola             8 non-null      int64
 4   vitoria                   8 non-null      bool
dtypes: bool(2), datetime64[ns](1), int64(2)
memory usage: 340.0 bytes

In [111]:
#Verifique se há alguma correlação entre a posse de bola e as vitórias quando Marcus Rashford está jogando:
dados_rashford

   jogo_id       data  marcus_rashford_em_campo  posse_de_bola  vitoria
0        1 2024-08-01                      True             55     True
1        2 2024-08-05                      True             48    False
2        3 2024-08-12                     False             52    False
3        4 2024-08-20                      True             63     True
4        5 2024-08-27                     False             45    False
5        6 2024-09-02                      True             57     True
6        7 2024-09-09                      True             60     True
7        8 2024-09-15                     False             49    False

In [114]:
posse_com_marcus = []
resultado_com_marcus = []

for i in range(len(dados_rashford['marcus_rashford_em_campo'])):
    if (dados_rashford['marcus_rashford_em_campo'][i] == True):
        posse_com_marcus.append(dados_rashford['posse_de_bola'][i])
        resultado_com_marcus.append(dados_rashford['vitoria'][i])

In [118]:
dicionario_rashford = {'Posse_Marcus': posse_com_marcus, 'Resultado_Marcus': resultado_com_marcus}

In [124]:
correlacao_rashford = pd.DataFrame(dicionario_rashford)
correlacao_rashford

   Posse_Marcus  Resultado_Marcus
0            55              True
1            48             False
2            63              True
3            57              True
4            60              True

In [125]:
correlacao = correlacao_rashford['Posse_Marcus'].corr(correlacao_rashford['Resultado_Marcus'])

In [126]:
print(f'Existe uma correlação de {round(correlacao, 2)} entre posse posse de vitórias quando Marcus Rashford atua.')

Existe uma correlação de 0.85 entre posse posse de vitórias quando Marcus Rashford atua.

## Média de assistências por jogo quando o time tem menos de 50% de posse de bola:

In [127]:
dados = {
    'jogo_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'data': ['2024-08-01', '2024-08-05', '2024-08-12', '2024-08-20', '2024-08-27', '2024-09-02', '2024-09-09', '2024-09-15'],
    'posse_de_bola': [55, 48, 49, 63, 45, 57, 40, 49],
    'assistencias': [2, 1, 1, 3, 0, 2, 0, 1]
}

In [128]:
dados_assistencia = pd.DataFrame(dados)

In [129]:
dados_assistencia

   jogo_id        data  posse_de_bola  assistencias
0        1  2024-08-01             55             2
1        2  2024-08-05             48             1
2        3  2024-08-12             49             1
3        4  2024-08-20             63             3
4        5  2024-08-27             45             0
5        6  2024-09-02             57             2
6        7  2024-09-09             40             0
7        8  2024-09-15             49             1

In [130]:
dados_assistencia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   jogo_id        8 non-null      int64
 1   data           8 non-null      object
 2   posse_de_bola  8 non-null      int64
 3   assistencias   8 non-null      int64
dtypes: int64(3), object(1)
memory usage: 388.0+ bytes

In [134]:
#Corrigindo parâmetro de datas:
dados_assistencia['data'] = pd.to_datetime(dados_assistencia['data'])

In [136]:
dados_assistencia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   jogo_id        8 non-null      int64
 1   data           8 non-null      datetime64[ns]
 2   posse_de_bola  8 non-null      int64
 3   assistencias   8 non-null      int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 388.0 bytes

In [138]:
#Calcule a média de assistências por jogo em partidas onde o Manchester United teve menos de 50% de posse de bola:
dados_assistencia

   jogo_id       data  posse_de_bola  assistencias
0        1 2024-08-01             55             2
1        2 2024-08-05             48             1
2        3 2024-08-12             49             1
3        4 2024-08-20             63             3
4        5 2024-08-27             45             0
5        6 2024-09-02             57             2
6        7 2024-09-09             40             0
7        8 2024-09-15             49             1

In [139]:
jogos_posse_menor_cinquenta = 0
quantidade_assistencias = 0

for i in range(len(dados_assistencia['posse_de_bola'])):
    if (dados_assistencia['posse_de_bola'][i] < 50):
        jogos_posse_menor_cinquenta = jogos_posse_menor_cinquenta + 1
        quantidade_assistencias = quantidade_assistencias + dados_assistencia['assistencias'][i]

In [141]:
assistencias_por_partida = quantidade_assistencias / jogos_posse_menor_cinquenta
assistencias_por_partida

0.6

In [143]:
print(f'A média de assistências por partida quando o time tem menos que 50% de posse de bola é de {assistencias_por_partida}.')

A média de assistências por partida quando o time tem menos que 50% de posse de bola é de 0.6.